language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - 2.2.2
before_install: gem update bundler
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c "create database rad_test;" -U postgres
  - bundle exec rake db:migrate
  - npm install
  - npm install -g bower karma-cli
  - bundle exec bowndler update
script:
  - bundle exec rspec
  - karma start spec/javascripts/karma.conf.js --single-run=true
