language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.5
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c "create database rad_test;" -U postgres
  - bundle exec rake db:migrate
  - npm install -g bower
  - bundle exec bowndler update
